version: '3.8'

services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
    environment:
        MARIADB_ROOT_PASSWORD: 123
        MARIADB_DATABASE: ecommerce

volumes:
  db_volume: