spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mariadb://localhost:3306/ecommerce
  application:
    name: ecommerce-api

app:
  jwt:
    secret: secret
    expiration: 2